#!/usr/bin/with-contenv bash

mkdir -p /var/lib/smartmontools/states /var/lib/smartmontools/attributelog

exec /usr/sbin/smartd --debug --savestates=/var/lib/smartmontools/states/ --attributelog=/var/lib/smartmontools/attributelog/
